version: '3'
services:
  config-server:
    build: config-server
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8090:8090

  eureka-server:
    build: eureka-server
    restart: always
#    depends_on:
#      - config-server
#      logging:
#        options:
#          max-size: "10m"
#          max-file: "10"
    ports:
      - 8092:8092

  gateway:
    build: gateway
    restart: always
    depends_on:
      - config-server
#      logging:
#        options:
#          max-size: "10m"
#          max-file: "10"
    ports:
      - 8095:8095

  microservice-user:
    build: microservice-user
    ports:
      - 8086:8086
    depends_on:
      - config-server
    restart: always
  microservice-event:
    build: microservice-event
    ports:
      - 8087:8087
    depends_on:
      - config-server
    restart: always
  microservice-client:
    build: microservice-client
    ports:
      - 8085:8085
    depends_on:
      - config-server
    restart: always
  my-sql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=soiree
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    restart: always
    command: mysqld --default_authentication_plugin=mysql_native_password
  microservice-soiree:
    build: microservice-soiree
    ports:
      - 8084:8084
    depends_on:
      - config-server
      - my-sql
    restart: always

volumes:
  db_data: {}